[[pre_commit]]
name = "NoDoNotCommit"
cmd = ["iprecommit-no-forbidden-strings", "--paths"]

[[pre_commit]]
name = "NewlineAtEndOfFile"
cmd = ["iprecommit-newline-at-eof"]
autofix = false
fail_fast = true
fix_cmd = ["iprecommit-newline-at-eof", "--fix"]

[[pre_commit]]
name = "CommonTypos"
cmd = ["iprecommit-typos", "--paths"]

[[pre_commit]]
name = "PythonFormat"
cmd = ["black", "--check"]
filters = ["*.py", "bin/ian.*"]
fix_cmd = ["black"]
autofix = false
fail_fast = true

[[pre_commit]]
name = "PythonTypesPyright"
cmd = ["bash", "-c", "source python/.venv/bin/activate && pyright"]
filters = ["*.py"]
pass_files = false

[[pre_commit]]
name = "PythonTests"
cmd = ["just", "test"]
filters = ["*.py"]
pass_files = false

# commit-msg checks
[[commit_msg]]
name = "CommitMessageFormat"
cmd = ["iprecommit-commit-msg-format", "--max-line-length", "72"]

[[commit_msg]]
name = "CommitMessageTypos"
cmd = ["iprecommit-typos", "--paths"]

# pre-push checks (run on commit messages)
[[pre_push]]
name = "NoDoNotPush"
cmd = ["iprecommit-no-forbidden-strings", "--strings", "DO NOT PUSH", "--commits"]
